<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/rrbot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>
<!--BRAZOOOOOOOOOOOOOOOOOOOO-->


<!-- Joint 0 -->
    <link name="left/arm_0_attachment">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/arm_0_attachment.stl" />
         </geometry>
          <origin rpy="0 0 0" xyz="0 0 0" />
      </visual>

          <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>

   <joint name="left/arm_0_attachment_joint" type="fixed">
      <parent link="world" />
      <child link="left/arm_0_attachment" />
      <origin rpy="0 0 0" xyz="0 0.6 1" />
   </joint>


    <link name="left/arm_0_top">
       <visual>
          <geometry>
             <mesh filename="package://arm_description/meshes/new_meshes/arm_0_top.stl"  />
          </geometry>
          <origin rpy="0 0 ${-pi/2}" xyz="0 0 0" />
       </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

    </link>
    <joint name="left/arm_0_top_joint" type="fixed">
       <parent link="left/arm_0_attachment" />
       <child link="left/arm_0_top" />
       <origin rpy="0 0 0" xyz="0 0 -0.03" />
    </joint>

    <link name="left/arm_0_bottom_top_lock">
       <visual>
          <geometry>
             <mesh filename="package://arm_description/meshes/new_meshes/arm_0_bottom_top_lock.stl"  />
          </geometry>
       </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

    </link>
    <joint name="left/arm_0_bottom_top_lock_joint" type="fixed">
       <parent link="left/arm_0_top" />
       <child link="left/arm_0_bottom_top_lock" />
       <origin rpy="0 0 0" xyz="0 0 0" />
    </joint>


   <link name="left/arm_0_bottom">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/arm_0_bottom.stl"  />
         </geometry>
         <origin rpy="0 ${pi/2} 0" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/arm_0_bottom_joint" type="continuous">
      <parent link="left/arm_0_bottom_top_lock" />
      <child link="left/arm_0_bottom" />
      <origin rpy="0 ${-pi/2} ${-pi/2}" xyz="0 0 -0.005" />
   </joint>

    <link name="left/arm_0_bottom_case">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/arm_0_bottom_case.stl"  />
         </geometry>
         <origin rpy="0 ${-pi/2} ${pi}" xyz="-0.015 0.0345 -0.025" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/arm_0_bottom_case_joint" type="fixed">
      <parent link="left/arm_0_bottom" />
      <child link="left/arm_0_bottom_case" />
      <origin rpy="0 0 0" xyz="-0.017 0 0" />
   </joint>

   
   <link name="left/arm_1">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/arm_1.stl"  />
         </geometry>
         <origin rpy="0 0 ${pi}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/arm_1_joint" type="continuous">
      <parent link="left/arm_0_bottom_case" />
      <child link="left/arm_1" />
      <origin xyz="0 0 0" rpy="0 ${3*pi/2} 0" />
   </joint>


 <link name="left/arm_1_case">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/arm_1_case.stl"  />
         </geometry>
         <origin rpy="${pi/2} 0 0" xyz="-0.02 -0.01 -0.035" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/arm_1_case_joint" type="fixed">
      <parent link="left/arm_1" />
      <child link="left/arm_1_case" />
      <origin xyz="0 0 0.145" rpy="0 0 0" />
   </joint>
   
   
   <link name="left/arm_2_microservo">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/arm_2_microservo.stl" />
         </geometry>
         <origin rpy="0 0 ${pi}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/arm_2_microservo_joint" type="continuous">
      <parent link="left/arm_1_case" />
      <child link="left/arm_2_microservo" />
      <origin xyz="0 0 0.0085" rpy="0 0 0"/>
   </joint>

<link name="left/arm_2_microservo_case">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/arm_2_microservo_case.stl" />
         </geometry>
         <origin rpy="0 0 0" xyz="0.027 -0.006 0" />
      </visual>


          <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
   </link>
   <joint name="left/arm_2_microservo_case_joint" type="fixed">
      <parent link="left/arm_2_microservo" />
      <child link="left/arm_2_microservo_case" />
      <origin xyz="0 0 0.057" rpy="0 0 0"/>
   </joint>

<link name="left/arm_2_case_bearing">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/arm_2_case_bearing.stl" />
         </geometry>
         <origin rpy="${pi/2} ${pi} ${pi/2}" xyz="0.027 -0.013 0.01" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/arm_2_case_bearing_joint" type="fixed">
      <parent link="left/arm_2_microservo_case" />
      <child link="left/arm_2_case_bearing" />
      <origin xyz="0 0 0.072" rpy="0 0 0"/>
   </joint>

<link name="left/end_effector_connector">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/end_effector_connector.stl" />
         </geometry>
         <origin rpy="0 0 0" xyz="0 0 -0.09" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/end_effector_connector_joint" type="fixed">
      <parent link="left/arm_2_case_bearing" />
      <child link="left/end_effector_connector" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
   </joint>



<link name="left/core_structure">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/core_structure.stl" />
         </geometry>
         <origin rpy="0 0 ${pi/2}" xyz="0.01 -0.01 0.018" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/core_structure_joint" type="fixed">
      <parent link="left/end_effector_connector" />
      <child link="left/core_structure" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
   </joint>

   <link name="left/base_gripper">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/base_gripper.stl" />
         </geometry>
         <origin rpy="0 0 ${-pi/2}" xyz="-0.02 0.0098 0.0171" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/base_gripper_joint" type="continuous">
      <parent link="left/core_structure" />
      <child link="left/base_gripper" />
      <origin xyz="0 0 0.041" rpy="0 0 ${-pi/2}"/>
   </joint>


<link name="left/microservo_FT">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/microservo_FT.stl" />
         </geometry>
         <origin rpy="0 0 0" xyz="0.0061 -0.032 0.008" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/microservo_FT_joint" type="fixed">
      <parent link="left/base_gripper" />
      <child link="left/microservo_FT" />
      <origin xyz="0 0 0.057" rpy="${pi/2} 0 ${pi/2}"/>
   </joint>

<link name="left/ScrewActuatorGripper">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/ScrewActuatorGripper.stl" />
         </geometry>
         <origin rpy="0 0 0" xyz="0.001 0 -0.0045" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/ScrewActuatorGripper_joint" type="fixed">
      <parent link="left/microservo_FT" />
      <child link="left/ScrewActuatorGripper" />
      <origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
   </joint>

<link name="left/base_gripper_case">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/base_gripper_case.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi}" xyz="-0.0145 0.02 0.004" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/base_gripper_case_joint" type="fixed">
      <parent link="left/ScrewActuatorGripper" />
      <child link="left/base_gripper_case" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
   </joint>

   <link name="left/ScrewActuatorGripperCenter">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/ScrewActuatorGripperCenter.stl" />
         </geometry>
         <origin rpy="0 0 0" xyz="-0.01 0.01 0.018" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/ScrewActuatorGripperCenter_joint" type="fixed">
      <parent link="left/ScrewActuatorGripper" />
      <child link="left/ScrewActuatorGripperCenter" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
   </joint>



<link name="left/holdBar_left">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/holdBar.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 -0.017 0.02" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/holdBar_left_joint" type="fixed">
      <parent link="left/base_gripper" />
      <child link="left/holdBar_left" />
      <origin xyz="0 -0.02 0.057" rpy="0 0 0"/>
   </joint>

   <link name="left/holdBar_right">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/holdBar.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${-pi/2}" xyz="0.005 0.017 0.02" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/holdBar_right_joint" type="fixed">
      <parent link="left/base_gripper" />
      <child link="left/holdBar_right" />
      <origin xyz="0 0.02 0.057" rpy="0 0 0"/>
   </joint>


   <link name="left/left_bar1">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/bar.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/left_bar1_joint" type="fixed">
      <parent link="left/holdBar_left" />
      <child link="left/left_bar1" />
      <origin xyz="0.005 -0.012 0.0265" rpy="0 0 0"/>
   </joint> 

<link name="left/left_bar2">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/bar.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/left_bar2_joint" type="fixed">
      <parent link="left/holdBar_left" />
      <child link="left/left_bar2" />
      <origin xyz="0.005 -0.022 0.0265" rpy="0 0 0"/>
   </joint>

<link name="left/left_bar3">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/bar.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/left_bar3_joint" type="fixed">
      <parent link="left/holdBar_left" />
      <child link="left/left_bar3" />
      <origin xyz="-0.005 -0.012 0.0265" rpy="0 0 0"/>
   </joint>

<link name="left/left_bar4">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/bar.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/left_bar4_joint" type="fixed">
      <parent link="left/holdBar_left" />
      <child link="left/left_bar4" />
      <origin xyz="-0.005 -0.022 0.0265" rpy="0 0 0"/>
</joint>

<link name="left/right_bar1">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/bar.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/right_bar1_joint" type="fixed">
      <parent link="left/holdBar_right" />
      <child link="left/right_bar1" />
      <origin xyz="0.005 0.012 0.0265" rpy="0 0 0"/>
   </joint>

<link name="left/right_bar2">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/bar.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/right_bar2_joint" type="fixed">
      <parent link="left/holdBar_right" />
      <child link="left/right_bar2" />
      <origin xyz="0.005 0.022 0.0265" rpy="0 0 0"/>
   </joint> 

<link name="left/right_bar3">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/bar.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/right_bar3_joint" type="fixed">
      <parent link="left/holdBar_right" />
      <child link="left/right_bar3" />
      <origin xyz="-0.005 0.012 0.0265" rpy="0 0 0"/>
   </joint>

<link name="left/right_bar4">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/bar.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/right_bar4_joint" type="fixed">
      <parent link="left/holdBar_right" />
      <child link="left/right_bar4" />
      <origin xyz="-0.005 0.022 0.0265" rpy="0 0 0"/>
</joint>     


<link name="left/left_barMini">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/barMini.stl" />
         </geometry>
         <origin rpy="${pi/2} 2.2 ${pi/2}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/left_barMini_joint" type="fixed">
      <parent link="left/left_bar1" />
      <child link="left/left_barMini" />
      <origin xyz="-0.0043 0 0.0155" rpy="0 0 0"/>
   </joint> 

<link name="left/right_barMini">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/barMini.stl" />
         </geometry>
         <origin rpy="${pi/2} -2.2 ${pi/2}" xyz="0 0 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/right_barMini_joint" type="fixed">
      <parent link="left/right_bar1" />
      <child link="left/right_barMini" />
      <origin xyz="-0.0043 0 0.0155" rpy="0 0 0"/>
   </joint>

<link name="left/left_gripper">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/gripper.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="0 -0.005 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/left_gripper_joint" type="continuous">
      <parent link="left/left_barMini" />
      <child link="left/left_gripper" />
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
</joint> 


<link name="left/right_gripper">
      <visual>
         <geometry>
            <mesh filename="package://arm_description/meshes/new_meshes/gripper/gripper.stl" />
         </geometry>
         <origin rpy="${pi/2} 0 ${pi/2}" xyz="-0.005 -0.005 0" />
      </visual>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

   </link>
   <joint name="left/right_gripper_joint" type="continuous">
      <parent link="left/right_barMini" />
      <child link="left/right_gripper" />
      <origin xyz="0 0 0.025" rpy="0 0 ${pi}"/>
</joint>



<!--BRAZOOOOOOOOOOOOOOOOOOOOooooooooooooooooooooooooooooooooooooooo-->

  <!-- Base Link -->
  <link name="link1">
    <!--collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision-->

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <!--collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision-->

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <!--collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision-->

    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${height3 - axel_offset/2}" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="hokuyo_link"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rrbot_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
  </joint>

  <link name="camera_link_optical">
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

<!--TRANSMISION BRAZO-->


<transmission name="tran_left/arm_0_bottom_joint">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left/arm_0_bottom_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_left/arm_0_bottom_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_left/arm_1_joint">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left/arm_1_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_left/arm_1_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

 <transmission name="tran_left/arm_2_microservo_joint">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left/arm_2_microservo_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_left/arm_2_microservo_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

   <transmission name="tran_left/base_gripper_joint">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left/base_gripper_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_left/base_gripper_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


   <transmission name="tran_left/left_gripper_joint">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left/left_gripper_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_left/left_gripper_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

   <transmission name="tran_left/right_gripper_joint">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left/right_gripper_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_left/right_gripper_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>